version: "3.7"

services:
  postgis:
    image: postgis/postgis
    env_file:
      - ./server/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - default

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres:
    name: postgres-db
