name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Build project
        run: yarn run build:prod
        env:
          FIREBASE_API_KEY: $${{env.FIREBASE_API_KEY}}
          FIREBASE_AUTH_DOMAIN: $${{env.FIREBASE_AUTH_DOMAIN}}
          FIREBASE_DATABASE_URL: $${{env.FIREBASE_DATABASE_URL}}
          FIREBASE_PROJECT_ID: $${{env.FIREBASE_PROJECT_ID}}
          FIREBASE_STORAGE_BUCKET: $${{env.FIREBASE_STORAGE_BUCKET}}
          FIREBASE_MESSAGING_SENDER_ID: $${{env.FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_APP_ID: $${{env.FIREBASE_APP_ID}}
          FIREBASE_MEASUREMENT_ID: $${{env.FIREBASE_MEASUREMENT_ID}}
          MAPBOX_ACCESS_TOKEN: $${{env.MAPBOX_ACCESS_TOKEN}}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WTMG_PRODUCTION }}'
          channelId: live
          projectId: wtmg-production
